export const properties = [
  {
    id: 1,
    slug: 'golden-arc-residences',
    title: 'Golden Arc Residences',
    price: '₹1.45 Cr',
    location: 'Golf Course Extension Road, Gurugram',
    type: 'Flats',
    category: 'Residential',
    purpose: 'Buy',
    size: '1,850 sq.ft.',
    bedrooms: 3,
    bathrooms: 3,
    area: 1850,
    budget: 14500000,
    featured: true,
    amenities: ['Clubhouse', 'Covered Parking', 'Power Backup', 'Modular Kitchen', 'Security'],
    images: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?auto=format&fit=crop&w=1200&q=80',
    ],
    description:
      'A premium ready-to-move apartment with refined interiors, high-floor views, and excellent connectivity to business districts, schools, and retail destinations.',
    map: 'https://maps.google.com/maps?q=Golf%20Course%20Extension%20Road%20Gurugram&t=&z=13&ie=UTF8&iwloc=&output=embed',
  },
  {
    id: 2,
    slug: 'elysian-villa-estate',
    title: 'Elysian Villa Estate',
    price: '₹4.8 Cr',
    location: 'DLF Phase 2, Gurugram',
    type: 'Villas',
    category: 'Residential',
    purpose: 'Buy',
    size: '4,200 sq.ft.',
    bedrooms: 5,
    bathrooms: 5,
    area: 4200,
    budget: 48000000,
    featured: true,
    amenities: ['Private Lawn', 'Home Office', 'Servant Room', 'Terrace Deck', 'Gated Security'],
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?auto=format&fit=crop&w=1200&q=80',
    ],
    description:
      'A spacious independent villa designed for private family living, featuring generous bedrooms, lush outdoor space, and tasteful material finishes.',
    map: 'https://maps.google.com/maps?q=DLF%20Phase%202%20Gurugram&t=&z=13&ie=UTF8&iwloc=&output=embed',
  },
  {
    id: 3,
    slug: 'signature-retail-bay',
    title: 'Signature Retail Bay',
    price: '₹2.25 L / month',
    location: 'Sohna Road, Gurugram',
    type: 'Commercial Properties',
    category: 'Commercial',
    purpose: 'Lease',
    size: '2,600 sq.ft.',
    bedrooms: 0,
    bathrooms: 2,
    area: 2600,
    budget: 225000,
    featured: false,
    amenities: ['Main Road Frontage', 'Lift Access', 'Fire Safety', 'Dedicated Parking', 'High Footfall'],
    images: [
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80',
    ],
    description:
      'A highly visible commercial unit suitable for retail, showroom, or service-led businesses with robust infrastructure and signage exposure.',
    map: 'https://maps.google.com/maps?q=Sohna%20Road%20Gurugram&t=&z=13&ie=UTF8&iwloc=&output=embed',
  },
  {
    id: 4,
    slug: 'sector-83-investment-plot',
    title: 'Sector 83 Investment Plot',
    price: '₹1.1 Cr',
    location: 'Sector 83, Faridabad',
    type: 'Plots',
    category: 'Residential',
    purpose: 'Sell',
    size: '240 sq.yd.',
    bedrooms: 0,
    bathrooms: 0,
    area: 2160,
    budget: 11000000,
    featured: false,
    amenities: ['Clear Title', 'Wide Road', 'Park Facing', 'Registry Ready', 'Utilities Nearby'],
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1472224371017-08207f84aaae?auto=format&fit=crop&w=1200&q=80',
    ],
    description:
      'A well-positioned residential plot with clean documentation and practical dimensions for a custom family home or long-term investment.',
    map: 'https://maps.google.com/maps?q=Sector%2083%20Faridabad&t=&z=13&ie=UTF8&iwloc=&output=embed',
  },
  {
    id: 5,
    slug: 'oakline-family-house',
    title: 'Oakline Family House',
    price: '₹65,000 / month',
    location: 'Greater Kailash, New Delhi',
    type: 'Independent Houses',
    category: 'Residential',
    purpose: 'Rent',
    size: '2,300 sq.ft.',
    bedrooms: 4,
    bathrooms: 4,
    area: 2300,
    budget: 65000,
    featured: true,
    amenities: ['Independent Entry', 'Balcony', 'Water Storage', 'Pet Friendly', 'Two Car Parking'],
    images: [
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
    ],
    description:
      'A warm, functional family home in an established neighbourhood, close to markets, parks, metro access, and everyday conveniences.',
    map: 'https://maps.google.com/maps?q=Greater%20Kailash%20New%20Delhi&t=&z=13&ie=UTF8&iwloc=&output=embed',
  },
  {
    id: 6,
    slug: 'nh8-commercial-land',
    title: 'NH8 Commercial Land Parcel',
    price: '₹7.2 Cr',
    location: 'NH8 Corridor, Manesar',
    type: 'Commercial Lands',
    category: 'Commercial',
    purpose: 'Buy',
    size: '1.5 acres',
    bedrooms: 0,
    bathrooms: 0,
    area: 65340,
    budget: 72000000,
    featured: false,
    amenities: ['Highway Access', 'Industrial Belt', 'Boundary Wall', 'Approach Road', 'Investment Grade'],
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80',
    ],
    description:
      'A strategic commercial land parcel with strong frontage and logistics-friendly access for warehousing, institutional, or mixed-use planning.',
    map: 'https://maps.google.com/maps?q=Manesar%20NH8&t=&z=13&ie=UTF8&iwloc=&output=embed',
  },
  {
    id: 7,
    slug: 'rosewood-by-trimont',
    title: 'Rosewood by Trimont',
    price: 'Rs. 58.83 Lac - Rs. 77.66 Lac',
    location: 'Sector 16, Bhiwadi',
    type: 'Flats',
    category: 'Residential',
    purpose: 'Buy',
    size: '1,250 - 1,650 sq.ft.',
    bedrooms: 4,
    bedroomLabel: '2/3/4 Beds',
    bathrooms: 3,
    bathroomLabel: '2/3 Baths',
    area: 1650,
    budget: 7766000,
    featured: true,
    status: 'Available',
    verified: true,
    possessionStatus: 'Under Construction',
    projectArea: '17 Acres',
    towers: '18 Towers',
    totalUnits: '450 Units',
    completion: 'September 2027',
    furnishing: 'Unfurnished',
    parking: '1 Garage',
    floorNumber: 'Ground + 14',
    totalFloors: '14',
    reraNumber: 'Verification assistance available',
    nearbyPlaces: [
      '5 min from NH 48, Delhi-Jaipur Highway',
      '5 min from proposed Alwar-Delhi RRTS Metro, Dharuhera',
      '35-40 min from Rajiv Chowk, Gurgaon',
      '60 min from Indira Gandhi International Airport',
      'Schools, hospitals, malls, and industrial hubs within 5-25 min',
    ],
    amenities: [
      'Grand Clubhouse',
      'Half Olympic-size Swimming Pool',
      'Pickleball Court',
      'Badminton Court',
      'Basketball Court',
      'Kids Play Area',
      'Open Gym',
      'Yoga Zone',
      'Jogging Track',
      'Landscaped Greens',
      'Reserved Parking',
      'Power Backup',
      'Security',
      'Visitor Parking',
      'Waste Disposal',
    ],
    images: [
      '/properties/rosewood/project-view.webp',
      '/properties/rosewood/pool-deck.webp',
      '/properties/rosewood/masterplan.webp',
      '/properties/rosewood/landscape-sports.webp',
      '/properties/rosewood/balcony-view.webp',
      '/properties/rosewood/basketball-court.webp',
      '/properties/rosewood/tennis-court.webp',
      '/properties/rosewood/location-map.webp',
    ],
    description:
      'Rosewood by Trimont is a thoughtfully planned under-construction residential apartment project in Sector 16, Bhiwadi, offering 2 BHK, 3 BHK and 4 BHK homes. Designed around open greens, large balconies, landscaped gardens, sports courts and a modern clubhouse, the project blends luxury, comfort and practical connectivity near Alwar Bypass Road and NH 48.',
    longDescription: [
      'Rosewood by Trimont is a seamless amalgamation of luxury, comfort and style, planned to provide a truly sophisticated lifestyle in Bhiwadi. These residential apartments are designed to create a calm, well-ventilated and uncluttered living environment, with open green spaces that make everyday life feel more relaxed and refined.',
      'Developed by Trimont Group on Alwar Bypass Road, Bhiwadi, the project focuses on customer satisfaction, quality standards, innovation and timely delivery. Trimont Rosewood offers 2 BHK, 3 BHK and 4 BHK apartments with large balconies, practical layouts, modern amenities and excellent public transport connectivity.',
      'Spread across a large residential campus with multiple towers, landscaped greens, a grand entrance, sports courts and a modern social hub, Trimont Rosewood is positioned as a strong residential and investment opportunity for buyers looking at Bhiwadi and the Alwar Bypass Road corridor.',
    ],
    projectHighlights: [
      '2/3/4 BHK apartments',
      'Project area of approx. 17 acres',
      '18 towers',
      'Ground + 14 storey towers',
      'More than 80% open area',
      'Located on 4 lane mega highway, 200 ft Alwar Bypass Road',
      'Beautifully landscaped gardens',
      'Grand entrance with water bodies',
      'Ultra modern club and swimming pool',
      'Large balconies',
      'Spacious lift lobby',
      '4 apartments on one floor with 2 lifts in 2 BHK apartments',
      '3 apartments on one floor with 2 lifts in 3 BHK apartments',
      'All tower structures ready',
      'Project completion expected in September 2027',
    ],
    socialHubAmenities: [
      'Approx. 150,000 sq.ft. social hub',
      'Grand clubhouse',
      'Half Olympic-size swimming pool',
      'Pickleball court',
      'Landscaped greens',
      'Kids play area',
      'Box cricket area',
      'Badminton court',
      'Basketball court',
      'Splash pool for kids',
      'Open gym',
      'Yoga zone',
      'Gazebo for senior citizens',
      'Sitting area',
      'Lawn',
      'Jogging/walking path',
      'Rose garden',
      'Golf cart',
    ],
    unitTypes: [
      '2 BHK - 1,250 sq.ft.',
      '3 BHK - 1,650 sq.ft.',
      '4 BHK - 2,750 sq.ft.',
    ],
    locationAdvantages: [
      'Bang on Alwar-Bhiwadi Road',
      '5 min drive from NH 48, Delhi-Jaipur Highway',
      '5 min from proposed Alwar-Delhi RRTS Metro, Dharuhera',
      '60 min from Indira Gandhi International Airport',
      '35-40 min from Rajiv Chowk, Gurgaon',
      'Proposed RRTS Metro Station at Dharuhera within 5 min',
      'Panchgaon proposed RRTS within 15 min',
      'IMT Manesar via proposed RRTS within 20 min',
      'GD Goenka Public School within 10 min',
      'Delhi Public School International within 15 min',
      'St. Xavier\'s School within 5 min',
      'Sri Krishna Hospital within 5 min',
      'Hari Ram Hospital within 5 min',
      'Genesis Mall within 3 min',
      'Legend Centra Mall within 2 min',
      'Reliance Smart Superstore within 2 min',
      'D Mart within 10 min',
      'Industrial hubs including KEI, Jaquar, Lenskart, Honda and Saint Gobain within 20-25 min',
    ],
    map: 'https://maps.google.com/maps?q=Sector%2016%20Bhiwadi%20Rajasthan&t=&z=14&ie=UTF8&iwloc=&output=embed',
  },
  {
    id: 8,
    slug: 'greenwood-city-bhiwadi-tijara-highway',
    title: 'Green Wood City Plotted Development',
    price: 'Rs. 12,900 per sq. yd.',
    location: 'Bhiwadi-Tijara Highway, SH-25, Bhiwadi',
    type: 'Plots',
    category: 'Residential',
    purpose: 'Buy',
    size: '105 - 200 sq. yd.',
    bedrooms: 0,
    bathrooms: 0,
    area: 1800,
    budget: 1354500,
    featured: true,
    status: 'Available',
    verified: true,
    possessionStatus: 'Launch Offer',
    projectArea: '9 Bigha plotted development',
    reraNumber: 'Verification assistance available',
    brochureUrl: '/properties/greenwood-city/brochure.pdf',
    videoUrl: '/properties/greenwood-city/site-video.mp4',
    amenities: [
      'Gated Community',
      'Wide Roads',
      'Park & Green Area',
      '24x7 Security',
      'Priority Allotment',
      'Limited Inventory',
      'Highway Location',
      'Investment Potential',
    ],
    images: [
      '/properties/greenwood-city/launch-offer.jpeg',
      '/properties/greenwood-city/site-plan.png',
    ],
    description:
      'Green Wood City is a premium plotted development launch on Bhiwadi-Tijara Highway, SH-25, offering limited plots with exclusive launch pricing and strong investment potential.',
    longDescription: [
      'Green Wood City is a premium plotted development launch located bang on SH-25, Bhiwadi-Tijara Highway. The project offers buyers an opportunity to own residential plots in a growing Bhiwadi corridor with highway visibility and strong future potential.',
      'The launch offer includes tentative plot sizes from approx. 105 to 200 sq. yds. at Rs. 12,900 per sq. yd., with an exclusive inaugural saving of Rs. 900 per sq. yd. for limited inventory. The offer is valid for the next 15 days only.',
      'This launch is positioned for buyers looking for priority allotment, lowest pricing in Bhiwadi, excellent investment potential and early access to the best plots in the township.',
    ],
    projectHighlights: [
      'Premium plotted development on Bhiwadi-Tijara Highway',
      'Bang on SH-25 Bhiwadi',
      'Tentative plot sizes approx. 105-200 sq. yds.',
      'Launch price Rs. 12,900 per sq. yd.',
      'Exclusive offer saves Rs. 900 per sq. yd.',
      'Offer valid for the next 15 days only',
      'Limited inventory available',
      'Priority allotment of best plots',
      'Lowest pricing in Bhiwadi',
      'Excellent investment potential',
    ],
    socialHubAmenities: [
      'Gated community',
      'Wide roads',
      'Park and green area',
      '24x7 security',
      'Plotted township planning',
      'Highway frontage advantage',
    ],
    unitTypes: [
      'Approx. 105 sq. yd. plots',
      'Approx. 150 sq. yd. plots',
      'Approx. 200 sq. yd. plots',
    ],
    locationAdvantages: [
      'Located on Bhiwadi-Tijara Highway',
      'Bang on SH-25 Bhiwadi',
      'Good visibility and access from highway corridor',
      'Suitable for residential investment and future appreciation',
      'Connected to Bhiwadi growth corridor',
    ],
    nearbyPlaces: [
      'Bhiwadi-Tijara Highway',
      'SH-25 Bhiwadi',
      'Bhiwadi growth corridor',
    ],
    legalNote: 'Registry charges, government charges and documentation charges payable extra as applicable.',
    map: 'https://www.google.com/maps/embed?pb=!1m17!1m12!1m3!1d1099.9102587864916!2d76.84115002508645!3d27.999277541820728!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m2!1m1!2zMjfCsDU5JzU1LjgiTiA3NsKwNTAnMjguMyJF!5e0!3m2!1sen!2sin!4v1783861768086!5m2!1sen!2sin',
  },
    {
      "id": 9,
      "slug": "trehan-vriksha-neemrana-residential-plots",
      "title": "Trehan Vriksha Neemrana Residential Plots",
      "price": "Rs 37,000 per sq yd",
      "location": "Neemrana",
      "type": "Plots",
      "category": "Residential",
      "purpose": "Buy",
      "size": "105 sq yd onwards",
      "bedrooms": 0,
      "bedroomLabel": "",
      "bathrooms": 0,
      "bathroomLabel": "",
      "area": 945,
      "budget": 3885000,
      "featured": true,
      "status": "Available",
      "verified": true,
      "possessionStatus": "Coming Soon",
      "furnishing": "",
      "parking": "Plot development",
      "ageOfProperty": "Coming soon",
      "facing": "On request",
      "floorNumber": "",
      "totalFloors": "",
      "reraNumber": "RERA registration expected / on request",
      "brochureUrl": "",
      "videoUrl": "",
      "floorPlanUrl": "/properties/trehan-vriksha-neemrana/location-map.webp",
      "images": [
        "/properties/trehan-vriksha-neemrana/cover.webp",
        "/properties/trehan-vriksha-neemrana/gallery-01.webp",
        "/properties/trehan-vriksha-neemrana/gallery-02.webp",
        "/properties/trehan-vriksha-neemrana/gallery-03.webp",
        "/properties/trehan-vriksha-neemrana/location-map.webp"
      ],
      "description": "Trehan Vriksha Neemrana is a coming-soon premium residential plotted township by Trehan Group on NH-48, Delhi-Jaipur Highway. Planned across more than 100 acres with the first phase over 40 acres, the township is expected to offer around 800 residential plots in 105 and 150 sq yd sizes. The project is positioned for buyers and investors looking for plotted ownership in a high-growth Neemrana location with broad internal roads, planned zoning, gated infrastructure, green spaces, landscaped gardens and long-term appreciation potential near major industrial and economic corridors.",
      "longDescription": [
        "Trehan Vriksha Neemrana is a coming-soon premium residential plotted township by Trehan Group on NH-48, Delhi-Jaipur Highway. Planned across more than 100 acres with the first phase over 40 acres, the township is expected to offer around 800 residential plots in 105 and 150 sq yd sizes. The project is positioned for buyers and investors looking for plotted ownership in a high-growth Neemrana location with broad internal roads, planned zoning, gated infrastructure, green spaces, landscaped gardens and long-term appreciation potential near major industrial and economic corridors."
      ],
      "amenities": [
        "Premium Township",
        "Gated Community",
        "Wide Internal Roads",
        "Planned Infrastructure",
        "Water Supply",
        "Underground Electrical Systems",
        "Laid Drainage Systems",
        "Clubhouse",
        "Green Open Spaces",
        "Landscaped Gardens",
        "NH-48 Connectivity",
        "Low-density Development"
      ],
      "nearbyPlaces": [
        "Delhi-Jaipur NH-48 - 0.5 km",
        "RIICO Industrial Area - 3 km",
        "Japanese Industrial Zone, Neemrana - 4 km",
        "St. Xavier's School, Neemrana - 4 km",
        "Modern Public School, Neemrana - 5 km",
        "NIIT University, Neemrana",
        "Park Hospital, Behror - 9 km",
        "Manohar Hospital Multi & Super Speciality Hospital - 3 km",
        "Soni Devi Memorial Hospital - 4 km",
        "Neemrana Fort - 8 km",
        "Neemrana City Center - 5 km",
        "Opposite Raath International School",
        "Near Hotel Tara"
      ],
      "projectHighlights": [
        "Available property",
        "Possession: Coming Soon",
        "Ownership: Freehold",
        "Area from 105 sq yd onwards",
        "Plot area: 105 and 150 sq yd",
        "Road width: Wide internal roads"
      ],
      "unitTypes": [
        "105 and 150 sq yd",
        "105 sq yd onwards"
      ],
      "socialHubAmenities": [
        "Premium Township",
        "Gated Community",
        "Wide Internal Roads",
        "Planned Infrastructure",
        "Water Supply",
        "Underground Electrical Systems",
        "Laid Drainage Systems",
        "Clubhouse",
        "Green Open Spaces",
        "Landscaped Gardens"
      ],
      "locationAdvantages": [
        "Delhi-Jaipur NH-48 - 0.5 km",
        "RIICO Industrial Area - 3 km",
        "Japanese Industrial Zone, Neemrana - 4 km",
        "St. Xavier's School, Neemrana - 4 km",
        "Modern Public School, Neemrana - 5 km",
        "NIIT University, Neemrana",
        "Park Hospital, Behror - 9 km",
        "Manohar Hospital Multi & Super Speciality Hospital - 3 km",
        "Soni Devi Memorial Hospital - 4 km",
        "Neemrana Fort - 8 km",
        "Neemrana City Center - 5 km",
        "Opposite Raath International School",
        "Near Hotel Tara"
      ],
      "legalNote": "Freehold. Verification assistance available.",
      "map": "https://maps.google.com/maps?q=NH-48%2C%20Delhi-Jaipur%20Highway%2C%20Fatehpura%2C%20Neemrana%2C%20Rajasthan&t=&z=13&ie=UTF8&iwloc=&output=embed"
    },
    {
      "id": 10,
      "slug": "trehan-luxury-floors-sector-35-sohna-gurgaon",
      "title": "Trehan Luxury Floors 3 BHK Builder Floor",
      "price": "Rs 1.85 Cr",
      "location": "Sector 35 Sohna Gurgaon",
      "type": "Flats",
      "category": "Residential",
      "purpose": "Buy",
      "size": "1760 sq ft",
      "bedrooms": 3,
      "bedroomLabel": "3 BHK",
      "bathrooms": 3,
      "bathroomLabel": "3 bathrooms",
      "area": 1760,
      "budget": 18500000,
      "featured": true,
      "status": "Available",
      "verified": true,
      "possessionStatus": "Ready to Move",
      "furnishing": "Premium fitted",
      "parking": "Stilt parking",
      "ageOfProperty": "May 2024 launch",
      "facing": "Aravalli view options",
      "floorNumber": "Low-rise luxury floor",
      "totalFloors": "Low-rise floors",
      "reraNumber": "Verification assistance available",
      "brochureUrl": "/brochures/trehan-luxury-floors-brochure.pdf",
      "videoUrl": "",
      "floorPlanUrl": "/properties/trehan-luxury-floors/floor-plan.jpeg",
      "images": [
        "/properties/trehan-luxury-floors/cover.avif",
        "/properties/trehan-luxury-floors/gallery-01.avif",
        "/properties/trehan-luxury-floors/gallery-02.avif",
        "/properties/trehan-luxury-floors/gallery-03.avif",
        "/properties/trehan-luxury-floors/gallery-04.avif",
        "/properties/trehan-luxury-floors/gallery-05.avif",
        "/properties/trehan-luxury-floors/gallery-06.avif",
        "/properties/trehan-luxury-floors/gallery-07.avif",
        "/properties/trehan-luxury-floors/gallery-08.avif",
        "/properties/trehan-luxury-floors/gallery-09.avif",
        "/properties/trehan-luxury-floors/gallery-10.avif",
        "/properties/trehan-luxury-floors/gallery-11.jpg",
        "/properties/trehan-luxury-floors/gallery-12.jpg",
        "/properties/trehan-luxury-floors/gallery-13.jpg",
        "/properties/trehan-luxury-floors/gallery-14.jpg",
        "/properties/trehan-luxury-floors/gallery-15.jpg",
        "/properties/trehan-luxury-floors/gallery-16.jpg",
        "/properties/trehan-luxury-floors/gallery-17.jpg",
        "/properties/trehan-luxury-floors/gallery-18.jpg"
      ],
      "description": "Trehan Luxury Floors by Trehan Builders Pvt Ltd is a premium ready-to-move residential project in Sector 35, Sohna, Gurgaon. The project offers spacious 3 BHK low-rise luxury floors of 1760 sq ft with premium finishes, smart home automation, imported marble flooring, stilt parking and scenic Aravalli views. Located on the Sohna-Gurgaon growth corridor, the project is positioned near schools, healthcare, retail and daily conveniences while offering a quieter low-rise lifestyle.",
      "longDescription": [
        "Trehan Luxury Floors by Trehan Builders Pvt Ltd is a premium ready-to-move residential project in Sector 35, Sohna, Gurgaon. The project offers spacious 3 BHK low-rise luxury floors of 1760 sq ft with premium finishes, smart home automation, imported marble flooring, stilt parking and scenic Aravalli views. Located on the Sohna-Gurgaon growth corridor, the project is positioned near schools, healthcare, retail and daily conveniences while offering a quieter low-rise lifestyle."
      ],
      "amenities": [
        "24X7 Water Supply",
        "Fire Sprinklers",
        "Power Backup",
        "Smart Home Automation",
        "Electric Car Charging Points",
        "Imported Marble Flooring",
        "20,000 sq ft Clubhouse",
        "Aravalli Views",
        "QRT Health Team",
        "Hospital Tie-up",
        "1-Year JLL Maintenance",
        "Stilt Parking",
        "Security",
        "Low-rise Community"
      ],
      "nearbyPlaces": [
        "GD Goenka Signature School - 5 mins / 4 km",
        "Sector 55-56 Metro Station - 23 mins / 22.2 km",
        "Vardaan Hospital & Trauma Centre - 8 mins / 6.4 km",
        "Global City Centre - 3 mins / 2.1 km",
        "Shivam Chilled Point",
        "DPS World School nearby",
        "KR Mangalam University nearby",
        "Prime Sohna-Gurgaon Road location",
        "Well-developed South Gurgaon area"
      ],
      "projectHighlights": [
        "Available property",
        "Possession: Ready to Move",
        "Ownership: Freehold",
        "Area from 1760 sq ft",
        "Configuration: 3 BHK"
      ],
      "unitTypes": [
        "3 BHK",
        "1760 sq ft"
      ],
      "socialHubAmenities": [
        "24X7 Water Supply",
        "Fire Sprinklers",
        "Power Backup",
        "Smart Home Automation",
        "Electric Car Charging Points",
        "Imported Marble Flooring",
        "20,000 sq ft Clubhouse",
        "Aravalli Views",
        "QRT Health Team",
        "Hospital Tie-up"
      ],
      "locationAdvantages": [
        "GD Goenka Signature School - 5 mins / 4 km",
        "Sector 55-56 Metro Station - 23 mins / 22.2 km",
        "Vardaan Hospital & Trauma Centre - 8 mins / 6.4 km",
        "Global City Centre - 3 mins / 2.1 km",
        "Shivam Chilled Point",
        "DPS World School nearby",
        "KR Mangalam University nearby",
        "Prime Sohna-Gurgaon Road location",
        "Well-developed South Gurgaon area"
      ],
      "legalNote": "Freehold. Verification assistance available.",
      "map": "https://maps.google.com/maps?q=Sector%2035%2C%20Sohna%2C%20Gurgaon%2C%20Haryana&t=&z=13&ie=UTF8&iwloc=&output=embed"
    },
    {
      "id": 11,
      "slug": "krish-aura-sector-18-bhiwadi",
      "title": "Krish Aura 1, 2 and 3 BHK Apartments",
      "price": "Rs 27.5 Lac - Rs 42.99 Lac",
      "location": "Sector 18 Bhiwadi",
      "type": "Flats",
      "category": "Residential",
      "purpose": "Buy",
      "size": "600 sq ft onwards",
      "bedrooms": 3,
      "bedroomLabel": "1/2/3 BHK",
      "bathrooms": 3,
      "bathroomLabel": "As per configuration",
      "area": 600,
      "budget": 2750000,
      "featured": true,
      "status": "Available",
      "verified": true,
      "possessionStatus": "Ready to Move",
      "furnishing": "Semi-furnished",
      "parking": "Car parking",
      "ageOfProperty": "Ready community",
      "facing": "3 open side options",
      "floorNumber": "G + 13 towers",
      "totalFloors": "5 buildings",
      "reraNumber": "Verification assistance available",
      "brochureUrl": "/brochures/krish-aura-brochure.pdf",
      "videoUrl": "",
      "floorPlanUrl": "",
      "images": [
        "/properties/krish-aura/cover.webp",
        "/properties/krish-aura/gallery-01.avif",
        "/properties/krish-aura/gallery-02.avif",
        "/properties/krish-aura/gallery-03.avif",
        "/properties/krish-aura/gallery-04.avif",
        "/properties/krish-aura/gallery-05.avif",
        "/properties/krish-aura/gallery-06.avif",
        "/properties/krish-aura/gallery-07.avif",
        "/properties/krish-aura/gallery-08.avif",
        "/properties/krish-aura/gallery-09.avif",
        "/properties/krish-aura/gallery-10.avif",
        "/properties/krish-aura/gallery-11.avif",
        "/properties/krish-aura/gallery-12.avif",
        "/properties/krish-aura/gallery-13.avif",
        "/properties/krish-aura/gallery-14.avif",
        "/properties/krish-aura/gallery-15.avif",
        "/properties/krish-aura/gallery-16.avif",
        "/properties/krish-aura/gallery-17.avif",
        "/properties/krish-aura/gallery-18.avif",
        "/properties/krish-aura/gallery-19.avif",
        "/properties/krish-aura/gallery-20.avif",
        "/properties/krish-aura/gallery-21.jpeg",
        "/properties/krish-aura/gallery-22.jpeg",
        "/properties/krish-aura/gallery-23.jpeg",
        "/properties/krish-aura/gallery-24.jpeg",
        "/properties/krish-aura/gallery-25.jpeg",
        "/properties/krish-aura/gallery-26.jpeg",
        "/properties/krish-aura/gallery-27.jpeg",
        "/properties/krish-aura/gallery-28.jpeg",
        "/properties/krish-aura/gallery-29.jpeg",
        "/properties/krish-aura/gallery-30.jpeg",
        "/properties/krish-aura/gallery-31.png",
        "/properties/krish-aura/gallery-32.png"
      ],
      "description": "Krish Aura by Krish Group is a ready-to-move apartment project on SH-25, Alwar Bypass Road, near Cosmos Greens, Sector 18, Bhiwadi. Spread across 4 acres with 80 percent open area, 5 buildings and 798 units, the project offers 1 BHK, 2 BHK and 3 BHK apartments sized from 600 to 1230 sq ft. The community is known for 3 open side homes, national park views, podium lifestyle amenities and everyday access to shopping, multiplexes, schools, hospitals and restaurants.",
      "longDescription": [
        "Krish Aura by Krish Group is a ready-to-move apartment project on SH-25, Alwar Bypass Road, near Cosmos Greens, Sector 18, Bhiwadi. Spread across 4 acres with 80 percent open area, 5 buildings and 798 units, the project offers 1 BHK, 2 BHK and 3 BHK apartments sized from 600 to 1230 sq ft. The community is known for 3 open side homes, national park views, podium lifestyle amenities and everyday access to shopping, multiplexes, schools, hospitals and restaurants."
      ],
      "amenities": [
        "Swimming Pool",
        "Fire Sprinklers",
        "Vastu Compliant",
        "Landscaping & Tree Planting",
        "Gymnasium",
        "Car Parking",
        "24X7 Water Supply",
        "Multipurpose Room",
        "Jogging Track",
        "Street Lighting",
        "Gated Community",
        "Security",
        "Power Backup",
        "Badminton Court",
        "Half Basketball Court",
        "Podium Amenities",
        "Garden",
        "Kids Play Area",
        "Dedicated Parking",
        "Lift"
      ],
      "nearbyPlaces": [
        "RPS School",
        "City Public School - 2 min drive",
        "RIICO - 10 min drive",
        "Hari Ram Hospital - 5 mins / 2.6 km",
        "Genesis Mall - 3 mins / 1.4 km",
        "McDonald's India",
        "Shopping, multiplexes and cineplex nearby",
        "Near Cosmos Greens",
        "Alwar Bypass Road connectivity"
      ],
      "projectHighlights": [
        "Available property",
        "Possession: Ready to Move",
        "Ownership: Freehold",
        "Area from 600 sq ft onwards",
        "Configuration: 1/2/3 BHK"
      ],
      "unitTypes": [
        "1/2/3 BHK",
        "600 sq ft onwards"
      ],
      "socialHubAmenities": [
        "Swimming Pool",
        "Fire Sprinklers",
        "Vastu Compliant",
        "Landscaping & Tree Planting",
        "Gymnasium",
        "Car Parking",
        "24X7 Water Supply",
        "Multipurpose Room",
        "Jogging Track",
        "Street Lighting"
      ],
      "locationAdvantages": [
        "RPS School",
        "City Public School - 2 min drive",
        "RIICO - 10 min drive",
        "Hari Ram Hospital - 5 mins / 2.6 km",
        "Genesis Mall - 3 mins / 1.4 km",
        "McDonald's India",
        "Shopping, multiplexes and cineplex nearby",
        "Near Cosmos Greens",
        "Alwar Bypass Road connectivity"
      ],
      "legalNote": "Freehold. Verification assistance available.",
      "map": "https://maps.google.com/maps?q=SH-25%2C%20Alwar%20Bypass%20Road%20Bhiwadi%2C%20Near%20Cosmos%20Greens%2C%20Sector%2018%2C%20Bhiwadi%2C%20Rajasthan&t=&z=13&ie=UTF8&iwloc=&output=embed"
    },
    {
      "id": 12,
      "slug": "krish-city-phase-2-tapukara-bhiwadi",
      "title": "Krish City Phase 2 1, 2 and 3 BHK Apartments",
      "price": "Rs 10.41 Lac - Rs 21.68 Lac",
      "location": "Tapukara Bhiwadi",
      "type": "Flats",
      "category": "Residential",
      "purpose": "Buy",
      "size": "485 sq ft onwards",
      "bedrooms": 3,
      "bedroomLabel": "1/2/3 BHK",
      "bathrooms": 3,
      "bathroomLabel": "As per configuration",
      "area": 485,
      "budget": 1041000,
      "featured": true,
      "status": "Available",
      "verified": true,
      "possessionStatus": "Ready to Move",
      "furnishing": "Semi-furnished",
      "parking": "Car parking",
      "ageOfProperty": "Ready community",
      "facing": "North-East / East options",
      "floorNumber": "Apartment towers",
      "totalFloors": "8 buildings",
      "reraNumber": "Verification assistance available",
      "brochureUrl": "/brochures/krish-city-phase-2-brochure.pdf",
      "videoUrl": "",
      "floorPlanUrl": "",
      "images": [
        "/properties/krish-city-phase-2/cover.avif",
        "/properties/krish-city-phase-2/gallery-01.avif",
        "/properties/krish-city-phase-2/gallery-02.avif",
        "/properties/krish-city-phase-2/gallery-03.avif",
        "/properties/krish-city-phase-2/gallery-04.avif",
        "/properties/krish-city-phase-2/gallery-05.avif",
        "/properties/krish-city-phase-2/gallery-06.avif",
        "/properties/krish-city-phase-2/gallery-07.avif",
        "/properties/krish-city-phase-2/gallery-08.avif",
        "/properties/krish-city-phase-2/gallery-09.avif",
        "/properties/krish-city-phase-2/gallery-10.avif",
        "/properties/krish-city-phase-2/gallery-11.avif",
        "/properties/krish-city-phase-2/gallery-12.avif",
        "/properties/krish-city-phase-2/gallery-13.avif",
        "/properties/krish-city-phase-2/gallery-14.avif",
        "/properties/krish-city-phase-2/gallery-15.avif",
        "/properties/krish-city-phase-2/gallery-16.avif",
        "/properties/krish-city-phase-2/gallery-17.avif",
        "/properties/krish-city-phase-2/gallery-18.avif",
        "/properties/krish-city-phase-2/gallery-19.avif",
        "/properties/krish-city-phase-2/gallery-20.avif",
        "/properties/krish-city-phase-2/gallery-21.avif",
        "/properties/krish-city-phase-2/gallery-22.avif",
        "/properties/krish-city-phase-2/gallery-23.avif",
        "/properties/krish-city-phase-2/gallery-24.avif",
        "/properties/krish-city-phase-2/gallery-25.avif",
        "/properties/krish-city-phase-2/gallery-26.avif",
        "/properties/krish-city-phase-2/gallery-27.avif",
        "/properties/krish-city-phase-2/gallery-28.avif",
        "/properties/krish-city-phase-2/gallery-29.avif",
        "/properties/krish-city-phase-2/gallery-30.jpeg"
      ],
      "description": "Krish City Phase 2 by Krish Group is a ready-to-move residential apartment project at SH-25, Alwar Bypass Road, Village Tapukara, Sector 93, Bhiwadi. Spread across 31 acres with 8 buildings and 1630 units, the project offers 1 BHK, 2 BHK and 3 BHK apartments sized from 485 to 1010 sq ft. The community is planned around landscaped gardens, wide internal roads, underground electrification, gated security and family-focused amenities, while staying central to four major industrial areas.",
      "longDescription": [
        "Krish City Phase 2 by Krish Group is a ready-to-move residential apartment project at SH-25, Alwar Bypass Road, Village Tapukara, Sector 93, Bhiwadi. Spread across 31 acres with 8 buildings and 1630 units, the project offers 1 BHK, 2 BHK and 3 BHK apartments sized from 485 to 1010 sq ft. The community is planned around landscaped gardens, wide internal roads, underground electrification, gated security and family-focused amenities, while staying central to four major industrial areas."
      ],
      "amenities": [
        "Internet / Wi-Fi",
        "Garbage Disposal",
        "Swimming Pool",
        "Olympic-sized Swimming Pool",
        "Vastu Compliant",
        "Landscaping & Tree Planting",
        "Gymnasium",
        "Fire Fighting System",
        "Medical Facilities",
        "School",
        "Car Parking",
        "24X7 Water Supply",
        "Gated Community",
        "Security",
        "Power Backup",
        "Lift",
        "Wide Internal Roads",
        "Underground Electrification",
        "Children's Play Area",
        "Community Hall",
        "Open Space",
        "Landscaped Gardens"
      ],
      "nearbyPlaces": [
        "Central to 4 major industrial areas",
        "Tapukara Hospital - 9 mins / 6.2 km",
        "Gera Hospital - 7 km",
        "Shri Makhan Bhog",
        "Tapukara locality",
        "Alwar Bypass Road connectivity",
        "Sector 93, Bhiwadi",
        "Milakpur Goojar nearby"
      ],
      "projectHighlights": [
        "Available property",
        "Possession: Ready to Move",
        "Ownership: Freehold",
        "Area from 485 sq ft onwards",
        "Configuration: 1/2/3 BHK"
      ],
      "unitTypes": [
        "1/2/3 BHK",
        "485 sq ft onwards"
      ],
      "socialHubAmenities": [
        "Internet / Wi-Fi",
        "Garbage Disposal",
        "Swimming Pool",
        "Olympic-sized Swimming Pool",
        "Vastu Compliant",
        "Landscaping & Tree Planting",
        "Gymnasium",
        "Fire Fighting System",
        "Medical Facilities",
        "School"
      ],
      "locationAdvantages": [
        "Central to 4 major industrial areas",
        "Tapukara Hospital - 9 mins / 6.2 km",
        "Gera Hospital - 7 km",
        "Shri Makhan Bhog",
        "Tapukara locality",
        "Alwar Bypass Road connectivity",
        "Sector 93, Bhiwadi",
        "Milakpur Goojar nearby"
      ],
      "legalNote": "Freehold. Verification assistance available.",
      "map": "https://maps.google.com/maps?q=SH-25%2C%20Alwar%20Bypass%20Road%2C%20Village%20Tapukara%2C%20Sector%2093%2C%20Bhiwadi%2C%20Rajasthan&t=&z=13&ie=UTF8&iwloc=&output=embed"
    },
    {
      "id": 13,
      "slug": "trehan-thd-garden-thara-bhiwadi",
      "title": "Trehan THD Garden 2 and 3 BHK Apartments",
      "price": "Rs 20 Lac - Rs 22 Lac",
      "location": "Thara Bhiwadi",
      "type": "Flats",
      "category": "Residential",
      "purpose": "Buy",
      "size": "750 sq ft onwards",
      "bedrooms": 3,
      "bedroomLabel": "2/3 BHK",
      "bathrooms": 3,
      "bathroomLabel": "2/3 bathrooms",
      "area": 750,
      "budget": 2000000,
      "featured": true,
      "status": "Available",
      "verified": true,
      "possessionStatus": "Ready to Move",
      "furnishing": "Semi-furnished",
      "parking": "1 garage / car parking",
      "ageOfProperty": "Ready community",
      "facing": "Vastu compliant options",
      "floorNumber": "Apartment towers",
      "totalFloors": "5 buildings",
      "reraNumber": "Verification assistance available",
      "brochureUrl": "/brochures/trehan-thd-garden-brochure.pdf",
      "videoUrl": "",
      "floorPlanUrl": "/properties/trehan-thd-garden/floor-plan.jpeg",
      "images": [
        "/properties/trehan-thd-garden/cover.avif",
        "/properties/trehan-thd-garden/gallery-01.avif",
        "/properties/trehan-thd-garden/gallery-02.avif"
      ],
      "description": "Trehan THD Garden at 8th Milestone, Bhiwadi-Alwar Bypass, Thara is a ready-to-move apartment project by Trehan Group. Spread across 9 acres with 5 buildings and 882 units, the community offers 2 BHK and 3 BHK apartments sized from 750 to 1389 sq ft. The project focuses on contemporary urban living in a lush green environment with spacious homes, cross ventilation, natural light, modern specifications and practical amenities for daily comfort.",
      "longDescription": [
        "Trehan THD Garden at 8th Milestone, Bhiwadi-Alwar Bypass, Thara is a ready-to-move apartment project by Trehan Group. Spread across 9 acres with 5 buildings and 882 units, the community offers 2 BHK and 3 BHK apartments sized from 750 to 1389 sq ft. The project focuses on contemporary urban living in a lush green environment with spacious homes, cross ventilation, natural light, modern specifications and practical amenities for daily comfort."
      ],
      "amenities": [
        "Children's Play Area",
        "Tennis Court",
        "Solar Lighting",
        "Garbage Disposal",
        "Swimming Pool",
        "Fountains",
        "Vastu Compliant",
        "Lift",
        "Landscaping & Tree Planting",
        "24x7 CCTV Surveillance",
        "Gymnasium",
        "Lush Greenery",
        "Discotheque",
        "Club House",
        "Power backup",
        "Car Parking",
        "Water Supply",
        "Security"
      ],
      "nearbyPlaces": [
        "Euro International School, Bhiwadi",
        "City Public School - 5 min drive",
        "Hari Ram Hospital - 10 mins / 6.4 km",
        "Genesis Mall",
        "McDonald's India",
        "Schools, multiplexes and cineplex nearby",
        "8th Milestone, Bhiwadi-Alwar Bypass"
      ],
      "projectHighlights": [
        "Available property",
        "Possession: Ready to Move",
        "Ownership: Freehold",
        "Area from 750 sq ft onwards",
        "Configuration: 2/3 BHK"
      ],
      "unitTypes": [
        "2/3 BHK",
        "750 sq ft onwards"
      ],
      "socialHubAmenities": [
        "Children's Play Area",
        "Tennis Court",
        "Solar Lighting",
        "Garbage Disposal",
        "Swimming Pool",
        "Fountains",
        "Vastu Compliant",
        "Lift",
        "Landscaping & Tree Planting",
        "24x7 CCTV Surveillance"
      ],
      "locationAdvantages": [
        "Euro International School, Bhiwadi",
        "City Public School - 5 min drive",
        "Hari Ram Hospital - 10 mins / 6.4 km",
        "Genesis Mall",
        "McDonald's India",
        "Schools, multiplexes and cineplex nearby",
        "8th Milestone, Bhiwadi-Alwar Bypass"
      ],
      "legalNote": "Freehold. Verification assistance available.",
      "map": "https://maps.google.com/maps?q=8th%20Milestone%2C%20Bhiwadi-Alwar%20Bypass%2C%20Thara%2C%20Alwar%20Bypass%20Road%2C%20Bhiwadi&t=&z=13&ie=UTF8&iwloc=&output=embed"
    },
    {
      "id": 14,
      "slug": "trehan-hill-view-garden-thara-bhiwadi",
      "title": "Trehan Hill View Garden Apartments",
      "price": "Rs 10 Lac - Rs 45 Lac",
      "location": "Thara Bhiwadi",
      "type": "Flats",
      "category": "Residential",
      "purpose": "Buy",
      "size": "600 sq ft onwards",
      "bedrooms": 3,
      "bedroomLabel": "2/3 BHK",
      "bathrooms": 3,
      "bathroomLabel": "2/3 bathrooms",
      "area": 600,
      "budget": 1000000,
      "featured": true,
      "status": "Available",
      "verified": true,
      "possessionStatus": "Ready to Move",
      "furnishing": "Semi-furnished",
      "parking": "1 garage / covered and open parking",
      "ageOfProperty": "Ready community",
      "facing": "Vastu compliant layout",
      "floorNumber": "Apartment towers",
      "totalFloors": "On request",
      "reraNumber": "Verification assistance available",
      "brochureUrl": "",
      "videoUrl": "",
      "floorPlanUrl": "",
      "images": [
        "/properties/trehan-hill-view-garden/cover.webp",
        "/properties/trehan-hill-view-garden/tower-view.webp",
        "/properties/trehan-hill-view-garden/night-courtyard.webp"
      ],
      "description": "Trehan Hill View Garden in Thara, Bhiwadi is a ready-to-move housing society with apartments and studio apartments across varied budget ranges. The project offers 1 BHK, 2 BHK and 3 BHK apartments along with 1 RK studio apartments, combining practical layouts, comfort and everyday convenience. Spread over 18.26 acres, the community includes more than 70 percent open green spaces and landscaped gardens, eco-friendly development, Vastu-compliant planning, a fully furnished clubhouse, supermarket, high-speed elevators, uninterrupted water supply and ample covered and open parking.",
      "longDescription": [
        "Trehan Hill View Garden in Thara, Bhiwadi is a ready-to-move housing society with apartments and studio apartments across varied budget ranges. The project offers 1 BHK, 2 BHK and 3 BHK apartments along with 1 RK studio apartments, combining practical layouts, comfort and everyday convenience. Spread over 18.26 acres, the community includes more than 70 percent open green spaces and landscaped gardens, eco-friendly development, Vastu-compliant planning, a fully furnished clubhouse, supermarket, high-speed elevators, uninterrupted water supply and ample covered and open parking."
      ],
      "amenities": [
        "24 hrs Power Backup",
        "Children's Play Area",
        "24x7 Security",
        "70% Open Green Area",
        "Firefighting System",
        "Exclusive Club",
        "Swimming Pool",
        "Gym",
        "Fitness Center",
        "Club House",
        "Green Parks",
        "Jogging Track",
        "Kids Play Area",
        "Power backup",
        "Tennis Courts",
        "Supermarket",
        "High Speed Elevators",
        "Water Supply",
        "Covered Parking",
        "Open Parking"
      ],
      "nearbyPlaces": [
        "Star Hospital - 5 km",
        "Sundar Lal Hospital - 3 km",
        "All major banks within 1 km radius",
        "Schools within 1 km radius",
        "Thara, Bhiwadi residential pocket"
      ],
      "projectHighlights": [
        "Available property",
        "Possession: Ready to Move",
        "Ownership: Freehold",
        "Area from 600 sq ft onwards",
        "Configuration: 2/3 BHK"
      ],
      "unitTypes": [
        "2/3 BHK",
        "600 sq ft onwards"
      ],
      "socialHubAmenities": [
        "24 hrs Power Backup",
        "Children's Play Area",
        "24x7 Security",
        "70% Open Green Area",
        "Firefighting System",
        "Exclusive Club",
        "Swimming Pool",
        "Gym",
        "Fitness Center",
        "Club House"
      ],
      "locationAdvantages": [
        "Star Hospital - 5 km",
        "Sundar Lal Hospital - 3 km",
        "All major banks within 1 km radius",
        "Schools within 1 km radius",
        "Thara, Bhiwadi residential pocket"
      ],
      "legalNote": "Freehold. Verification assistance available.",
      "map": "https://maps.google.com/maps?q=Thara%2C%20Bhiwadi%2C%20Rajasthan&t=&z=13&ie=UTF8&iwloc=&output=embed"
    },
    {
      "id": 15,
      "slug": "trehan-residences-sector-94-bhiwadi",
      "title": "Trehan Residences 2 and 3 BHK Builder Floors",
      "price": "Rs 19.25 Lac - Rs 45 Lac",
      "location": "Sector 94 Bhiwadi",
      "type": "Flats",
      "category": "Residential",
      "purpose": "Buy",
      "size": "712 sq ft onwards",
      "bedrooms": 3,
      "bedroomLabel": "2/3 BHK",
      "bathrooms": 2,
      "bathroomLabel": "2 bathrooms",
      "area": 712,
      "budget": 1925000,
      "featured": true,
      "status": "Available",
      "verified": true,
      "possessionStatus": "Ready to Move",
      "furnishing": "Fully / Semi-furnished options",
      "parking": "1 garage / car parking",
      "ageOfProperty": "2023 remodel",
      "facing": "Two-side open options",
      "floorNumber": "Low-rise floors",
      "totalFloors": "Low-rise community",
      "reraNumber": "Verification assistance available",
      "brochureUrl": "",
      "videoUrl": "",
      "floorPlanUrl": "",
      "images": [
        "/properties/trehan-vivanta-residences/cover.webp",
        "/properties/trehan-vivanta-residences/building.webp",
        "/properties/trehan-vivanta-residences/swimming-pool.webp",
        "/properties/trehan-vivanta-residences/internal-road.webp",
        "/properties/trehan-vivanta-residences/green-courtyard.webp"
      ],
      "description": "Trehan Residences in Sector 94, Bhiwadi offers ready-to-move 2 BHK and 3 BHK low-rise builder floors designed for comfortable modern living. The community combines practical layouts, green surroundings, recreational amenities and strong access to Alwar-Bhiwadi Road. Homes are planned with earthquake-resistant RCC frame structure, concealed copper wiring, sufficient light and power points, painted doors and windows, oil-bound distemper inside walls and a low-maintenance exterior finish. With club facilities, sports areas, swimming pool, green courtyard and family-focused amenities, Trehan Residences is suited for buyers looking for a ready residential option in Bhiwadi.",
      "longDescription": [
        "Trehan Residences in Sector 94, Bhiwadi offers ready-to-move 2 BHK and 3 BHK low-rise builder floors designed for comfortable modern living. The community combines practical layouts, green surroundings, recreational amenities and strong access to Alwar-Bhiwadi Road. Homes are planned with earthquake-resistant RCC frame structure, concealed copper wiring, sufficient light and power points, painted doors and windows, oil-bound distemper inside walls and a low-maintenance exterior finish. With club facilities, sports areas, swimming pool, green courtyard and family-focused amenities, Trehan Residences is suited for buyers looking for a ready residential option in Bhiwadi."
      ],
      "amenities": [
        "Air Conditioning",
        "Badminton Court",
        "Basketball Court",
        "Car Parking",
        "Club House",
        "Green Parks",
        "Gym",
        "Indoor Games",
        "Jogging Track",
        "Kids Play Area",
        "Landscaped Garden",
        "Lawn",
        "Multipurpose Hall",
        "Party Hall",
        "Power backup",
        "Swimming Pool",
        "Table Tennis",
        "Volleyball Court",
        "Yoga Park",
        "Cricket Practice Pitch",
        "Commercial Market",
        "Temple",
        "Amphitheater",
        "Water Supply",
        "WiFi"
      ],
      "nearbyPlaces": [
        "Bang on Alwar-Bhiwadi Road",
        "Gurgaon - 45 min",
        "Manesar - 40 min",
        "KMP Expressway - 30 min",
        "Dharuhera - 20 min",
        "Alwar Bypass Road - 20 min",
        "Nahar Industry - 10 min",
        "Honda Car Plant - 5 min"
      ],
      "projectHighlights": [
        "Available property",
        "Possession: Ready to Move",
        "Ownership: Freehold",
        "Area from 712 sq ft onwards",
        "Configuration: 2/3 BHK"
      ],
      "unitTypes": [
        "2/3 BHK",
        "712 sq ft onwards"
      ],
      "socialHubAmenities": [
        "Air Conditioning",
        "Badminton Court",
        "Basketball Court",
        "Car Parking",
        "Club House",
        "Green Parks",
        "Gym",
        "Indoor Games",
        "Jogging Track",
        "Kids Play Area"
      ],
      "locationAdvantages": [
        "Bang on Alwar-Bhiwadi Road",
        "Gurgaon - 45 min",
        "Manesar - 40 min",
        "KMP Expressway - 30 min",
        "Dharuhera - 20 min",
        "Alwar Bypass Road - 20 min",
        "Nahar Industry - 10 min",
        "Honda Car Plant - 5 min"
      ],
      "legalNote": "Freehold. Verification assistance available.",
      "map": "https://maps.google.com/maps?q=Sector%2094%2C%20Bhiwadi%2C%20Rajasthan&t=&z=13&ie=UTF8&iwloc=&output=embed"
    },
    {
      "id": 16,
      "slug": "trehan-vilasa-heights-fatehpura-neemrana",
      "title": "Trehan Vilasa Heights 2 BHK Apartments",
      "price": "Rs 26.74 Lac - Rs 29.75 Lac",
      "location": "Fatehpura Neemrana",
      "type": "Flats",
      "category": "Residential",
      "purpose": "Buy",
      "size": "965 sq ft",
      "bedrooms": 2,
      "bedroomLabel": "",
      "bathrooms": 2,
      "bathroomLabel": "",
      "area": 965,
      "budget": 2674000,
      "featured": true,
      "status": "Available",
      "verified": true,
      "possessionStatus": "Ready to Move",
      "furnishing": "Semi-furnished",
      "parking": "Car parking",
      "ageOfProperty": "2025 launch",
      "facing": "North-East / East options",
      "floorNumber": "1 to 12",
      "totalFloors": "12",
      "reraNumber": "Verification assistance available",
      "brochureUrl": "",
      "videoUrl": "",
      "floorPlanUrl": "/properties/trehan-vilasa-heights/gallery-01.avif",
      "images": [
        "/properties/trehan-vilasa-heights/cover.avif",
        "/properties/trehan-vilasa-heights/gallery-01.avif",
        "/properties/trehan-vilasa-heights/gallery-02.avif",
        "/properties/trehan-vilasa-heights/gallery-03.avif",
        "/properties/trehan-vilasa-heights/gallery-04.avif",
        "/properties/trehan-vilasa-heights/gallery-05.avif",
        "/properties/trehan-vilasa-heights/gallery-06.avif",
        "/properties/trehan-vilasa-heights/gallery-07.avif",
        "/properties/trehan-vilasa-heights/gallery-08.avif",
        "/properties/trehan-vilasa-heights/gallery-09.avif",
        "/properties/trehan-vilasa-heights/gallery-10.avif",
        "/properties/trehan-vilasa-heights/gallery-11.avif",
        "/properties/trehan-vilasa-heights/gallery-12.avif",
        "/properties/trehan-vilasa-heights/gallery-13.avif",
        "/properties/trehan-vilasa-heights/gallery-14.avif",
        "/properties/trehan-vilasa-heights/gallery-15.avif",
        "/properties/trehan-vilasa-heights/gallery-16.avif",
        "/properties/trehan-vilasa-heights/gallery-17.avif",
        "/properties/trehan-vilasa-heights/gallery-18.avif",
        "/properties/trehan-vilasa-heights/gallery-19.avif",
        "/properties/trehan-vilasa-heights/gallery-20.avif",
        "/properties/trehan-vilasa-heights/gallery-21.avif",
        "/properties/trehan-vilasa-heights/gallery-22.avif",
        "/properties/trehan-vilasa-heights/gallery-23.avif",
        "/properties/trehan-vilasa-heights/gallery-24.avif",
        "/properties/trehan-vilasa-heights/gallery-25.avif",
        "/properties/trehan-vilasa-heights/gallery-26.avif"
      ],
      "description": "Trehan Vilasa Heights in Fatehpura, NH-8, Neemrana offers ready-to-move 2 BHK apartments with efficient 965 sq ft layouts, cross ventilation, natural light and smart green features. The project is planned as one building with 108 units and gives easy access to Delhi-Jaipur Highway, the proposed RRTS Metro corridor, RIICO and Japanese Zone. Residents benefit from wide internal roads, green parks, open gym, clubhouse facilities and everyday conveniences near schools, healthcare, shopping and restaurants.",
      "longDescription": [
        "Trehan Vilasa Heights in Fatehpura, NH-8, Neemrana offers ready-to-move 2 BHK apartments with efficient 965 sq ft layouts, cross ventilation, natural light and smart green features. The project is planned as one building with 108 units and gives easy access to Delhi-Jaipur Highway, the proposed RRTS Metro corridor, RIICO and Japanese Zone. Residents benefit from wide internal roads, green parks, open gym, clubhouse facilities and everyday conveniences near schools, healthcare, shopping and restaurants."
      ],
      "amenities": [
        "Children's Play Area",
        "Partial Power Backup",
        "Swimming Pool",
        "Theme Park",
        "Landscaping & Tree Planting",
        "Lift",
        "Badminton Court",
        "24x7 CCTV Surveillance",
        "Fire Fighting System",
        "24X7 Water Supply",
        "Car Parking",
        "Open Gym",
        "Club House",
        "Efficient Lighting",
        "Green Park",
        "Wide Roads"
      ],
      "nearbyPlaces": [
        "Easy access to Delhi-Jaipur Highway",
        "Proximity to proposed RRTS Metro",
        "Within 7 km of RIICO and Japanese Area",
        "Raath International School, Behror",
        "Sachkhand Hospital",
        "Neemrana Plaza",
        "Hotel Highway King, Neemrana",
        "Renowned schools nearby",
        "Healthcare nearby",
        "30, 40 and 60 feet wide roads"
      ],
      "projectHighlights": [
        "Available property",
        "Possession: Ready to Move",
        "Ownership: Freehold",
        "Area from 965 sq ft"
      ],
      "unitTypes": [
        "965 sq ft"
      ],
      "socialHubAmenities": [
        "Children's Play Area",
        "Partial Power Backup",
        "Swimming Pool",
        "Theme Park",
        "Landscaping & Tree Planting",
        "Lift",
        "Badminton Court",
        "24x7 CCTV Surveillance",
        "Fire Fighting System",
        "24X7 Water Supply"
      ],
      "locationAdvantages": [
        "Easy access to Delhi-Jaipur Highway",
        "Proximity to proposed RRTS Metro",
        "Within 7 km of RIICO and Japanese Area",
        "Raath International School, Behror",
        "Sachkhand Hospital",
        "Neemrana Plaza",
        "Hotel Highway King, Neemrana",
        "Renowned schools nearby",
        "Healthcare nearby",
        "30, 40 and 60 feet wide roads"
      ],
      "legalNote": "Freehold. Verification assistance available.",
      "map": "https://maps.google.com/maps?q=Fatehpura%2C%20NH-8%2C%20Neemrana%2C%20Rajasthan&t=&z=13&ie=UTF8&iwloc=&output=embed"
    },
    {
      "id": 17,
      "slug": "trehan-vista-sector-54-bhiwadi",
      "title": "Trehan Vista 2 BHK Builder Floors",
      "price": "Rs 17.69 Lac - Rs 19.69 Lac",
      "location": "Sector 54 Bhiwadi",
      "type": "Flats",
      "category": "Residential",
      "purpose": "Buy",
      "size": "735 sq ft",
      "bedrooms": 2,
      "bedroomLabel": "",
      "bathrooms": 2,
      "bathroomLabel": "",
      "area": 735,
      "budget": 1769000,
      "featured": true,
      "status": "Available",
      "verified": true,
      "possessionStatus": "Ready to Move",
      "furnishing": "Semi-furnished",
      "parking": "1 garage / car parking",
      "ageOfProperty": "2024",
      "facing": "On request",
      "floorNumber": "Ground to 3rd",
      "totalFloors": "G + 3",
      "reraNumber": "Verification assistance available",
      "brochureUrl": "",
      "videoUrl": "",
      "floorPlanUrl": "/properties/trehan-vista/floor-plan.webp",
      "images": [
        "/properties/trehan-vista/entrance.webp",
        "/properties/trehan-vista/building.webp",
        "/properties/trehan-vista/bedroom.webp",
        "/properties/trehan-vista/balcony.webp",
        "/properties/trehan-vista/green-park.webp",
        "/properties/trehan-vista/table-tennis.webp",
        "/properties/trehan-vista/kids-play-room.webp",
        "/properties/trehan-vista/floor-plan.webp"
      ],
      "description": "Trehan Vista, Bhiwadi offers modern 2 BHK builder floors in Sector 54 with a practical 735 sq ft layout. The G+3 residential community is designed for comfortable family living with sports facilities, fitness areas, green parks, leisure zones and daily conveniences. Residents get access to a commercial market, kids play spaces, clubhouse, party hall, temple, amphitheater, swimming pool and yoga park, creating a balanced lifestyle near Honda Car Plant and key Bhiwadi industrial hubs.",
      "longDescription": [
        "Trehan Vista, Bhiwadi offers modern 2 BHK builder floors in Sector 54 with a practical 735 sq ft layout. The G+3 residential community is designed for comfortable family living with sports facilities, fitness areas, green parks, leisure zones and daily conveniences. Residents get access to a commercial market, kids play spaces, clubhouse, party hall, temple, amphitheater, swimming pool and yoga park, creating a balanced lifestyle near Honda Car Plant and key Bhiwadi industrial hubs."
      ],
      "amenities": [
        "Badminton Court",
        "Basketball Court",
        "Car Parking",
        "Green Parks",
        "Gym",
        "Kids Play Area",
        "Kids Play Room",
        "Landscaped Garden",
        "Party Lawn",
        "Party Hall",
        "Power backup",
        "Swimming Pool",
        "Water Supply",
        "Yoga Room",
        "Table Tennis",
        "Cricket Pitch",
        "Clubhouse",
        "Amphitheater",
        "Temple"
      ],
      "nearbyPlaces": [
        "Near Honda Car Plant",
        "Star Hospital",
        "Hari Ram Hospital",
        "OM Hospital",
        "BMR Hospital 24X7",
        "Shree Vinayak Hospital",
        "Honda Car & Honda Bike",
        "Shree Cement",
        "Supreme Furniture",
        "Dr. Oetker",
        "Lloyds",
        "Delhi Public School",
        "Presidency School",
        "St. Xavier's School",
        "Euro International School",
        "GD Goenka School"
      ],
      "projectHighlights": [
        "Available property",
        "Possession: Ready to Move",
        "Ownership: Freehold",
        "Area from 735 sq ft"
      ],
      "unitTypes": [
        "735 sq ft"
      ],
      "socialHubAmenities": [
        "Badminton Court",
        "Basketball Court",
        "Car Parking",
        "Green Parks",
        "Gym",
        "Kids Play Area",
        "Kids Play Room",
        "Landscaped Garden",
        "Party Lawn",
        "Party Hall"
      ],
      "locationAdvantages": [
        "Near Honda Car Plant",
        "Star Hospital",
        "Hari Ram Hospital",
        "OM Hospital",
        "BMR Hospital 24X7",
        "Shree Vinayak Hospital",
        "Honda Car & Honda Bike",
        "Shree Cement",
        "Supreme Furniture",
        "Dr. Oetker",
        "Lloyds",
        "Delhi Public School",
        "Presidency School",
        "St. Xavier's School",
        "Euro International School",
        "GD Goenka School"
      ],
      "legalNote": "Freehold. Verification assistance available.",
      "map": "https://maps.google.com/maps?q=Sector%2054%2C%20Bhiwadi%2C%20Rajasthan&t=&z=13&ie=UTF8&iwloc=&output=embed"
    },
    {
      "id": 18,
      "slug": "trehan-heights-sector-94-bhiwadi",
      "title": "Trehan Heights 2 BHK Apartments",
      "price": "Rs 23.79 Lac - Rs 25.2 Lac",
      "location": "Bhiwadi",
      "type": "Flats",
      "category": "Residential",
      "purpose": "Buy",
      "size": "701 sq ft",
      "bedrooms": 2,
      "bedroomLabel": "",
      "bathrooms": 2,
      "bathroomLabel": "",
      "area": 701,
      "budget": 2379000,
      "featured": true,
      "status": "Available",
      "verified": true,
      "possessionStatus": "Under Construction",
      "furnishing": "Semi-furnished",
      "parking": "1 garage / car parking",
      "ageOfProperty": "New construction",
      "facing": "On request",
      "floorNumber": "1 to 10",
      "totalFloors": "Stilt + 10",
      "reraNumber": "Verification assistance available",
      "brochureUrl": "",
      "videoUrl": "",
      "floorPlanUrl": "/properties/trehan-heights/floor-plan.webp",
      "images": [
        "/properties/trehan-heights/tower-view-1.webp",
        "/properties/trehan-heights/tower-view-2.webp",
        "/properties/trehan-heights/living-room-1.webp",
        "/properties/trehan-heights/living-room-2.webp",
        "/properties/trehan-heights/bedroom-1.webp",
        "/properties/trehan-heights/bedroom-2.webp",
        "/properties/trehan-heights/floor-plan.webp",
        "/properties/trehan-heights/site-plan.webp"
      ],
      "description": "Trehan Heights Bhiwadi redefines affordable luxury with thoughtfully crafted 2 BHK apartments in Sector 94, Bhiwadi. The project offers modern elevation, quality construction, practical connectivity and a lifestyle-focused rooftop terrace garden designed for relaxation, community time and panoramic views. Homes include spacious rooms, two toilets, air-conditioning provision, modular kitchen finishes and a construction-linked payment plan. Buyers may also be eligible for subsidy benefits up to Rs 1.80 Lacs under the PMAY scheme, subject to applicable rules.",
      "longDescription": [
        "Trehan Heights Bhiwadi redefines affordable luxury with thoughtfully crafted 2 BHK apartments in Sector 94, Bhiwadi. The project offers modern elevation, quality construction, practical connectivity and a lifestyle-focused rooftop terrace garden designed for relaxation, community time and panoramic views. Homes include spacious rooms, two toilets, air-conditioning provision, modular kitchen finishes and a construction-linked payment plan. Buyers may also be eligible for subsidy benefits up to Rs 1.80 Lacs under the PMAY scheme, subject to applicable rules."
      ],
      "amenities": [
        "Air Conditioning",
        "Badminton Court",
        "Car Parking",
        "Club House",
        "Green Parks",
        "Gym",
        "Jogging Track",
        "Kids Play Area",
        "Landscaped Garden",
        "Lawn",
        "Multipurpose Hall",
        "Power backup",
        "Swimming Pool",
        "Tennis Courts",
        "Water Supply",
        "Gated colony with security",
        "Yoga Area",
        "Open Gym",
        "Swings",
        "Play Ground",
        "Private Garden"
      ],
      "nearbyPlaces": [
        "Bang on Alwar-Bhiwadi Road",
        "Gurgaon - 45 min",
        "Manesar - 40 min",
        "KMP Expressway - 30 min",
        "Dharuhera - 20 min",
        "Alwar Bypass Road - 20 min",
        "Nahar Industry - 10 min",
        "Honda Car Plant - 5 min"
      ],
      "projectHighlights": [
        "Available property",
        "Possession: Under Construction",
        "Ownership: Freehold",
        "Area from 701 sq ft"
      ],
      "unitTypes": [
        "701 sq ft"
      ],
      "socialHubAmenities": [
        "Air Conditioning",
        "Badminton Court",
        "Car Parking",
        "Club House",
        "Green Parks",
        "Gym",
        "Jogging Track",
        "Kids Play Area",
        "Landscaped Garden",
        "Lawn"
      ],
      "locationAdvantages": [
        "Bang on Alwar-Bhiwadi Road",
        "Gurgaon - 45 min",
        "Manesar - 40 min",
        "KMP Expressway - 30 min",
        "Dharuhera - 20 min",
        "Alwar Bypass Road - 20 min",
        "Nahar Industry - 10 min",
        "Honda Car Plant - 5 min"
      ],
      "legalNote": "Freehold. Verification assistance available.",
      "map": "https://maps.google.com/maps?q=Sector%2094%2C%20Bhiwadi%2C%20Rajasthan&t=&z=13&ie=UTF8&iwloc=&output=embed"
    },
  {
    id: 19,
    slug: 'trehan-delight-residency-tapukara-bhiwadi',
    title: 'Trehan Delight Residency',
    price: 'Rs 17.58 Lac onwards',
    location: 'Tapukara, Alwar Bypass Road, Bhiwadi',
    type: 'Flats',
    category: 'Residential',
    purpose: 'Buy',
    size: '496 - 750 sq.ft.',
    bedrooms: 2,
    bedroomLabel: '2 BHK',
    bathrooms: 2,
    bathroomLabel: '2 Bathrooms',
    area: 750,
    budget: 1758000,
    featured: true,
    status: 'Available',
    verified: true,
    possessionStatus: 'Ready to Move',
    projectArea: '5 Acres with approx. 70% open area',
    towers: 'Trehan Delight Residence Tower D',
    totalUnits: '1 Building',
    completion: 'Ready to Move',
    furnishing: 'Semi-furnished options',
    parking: 'Car Parking',
    ageOfProperty: 'Launched Jan 2014',
    facing: 'North-East facing options',
    floorNumber: 'Available options up to 13th floor',
    totalFloors: 'On request',
    reraNumber: 'RAJ/P/2017/192',
    brochureUrl: '/brochures/trehan-delight-residency-brochure.pdf',
    floorPlanUrl: '/properties/trehan-delight-residency/gallery-01.avif',
    images: [
      '/properties/trehan-delight-residency/cover.avif',
      '/properties/trehan-delight-residency/gallery-01.avif',
      '/properties/trehan-delight-residency/gallery-02.avif',
      '/properties/trehan-delight-residency/gallery-03.avif',
      '/properties/trehan-delight-residency/gallery-04.avif',
      '/properties/trehan-delight-residency/gallery-05.avif',
      '/properties/trehan-delight-residency/gallery-06.avif',
      '/properties/trehan-delight-residency/gallery-07.avif',
      '/properties/trehan-delight-residency/gallery-08.avif',
      '/properties/trehan-delight-residency/gallery-09.avif',
    ],
    description:
      'Trehan Delight Residency by Trehan Group is a ready-to-move residential apartment project in Tapukara, Alwar Bypass Road, Bhiwadi. Spread across approx. 5 acres with nearly 70% open area, the project offers practical 2 BHK apartments with everyday amenities, strong local connectivity, and RERA registration RAJ/P/2017/192.',
    longDescription: [
      'Trehan Delight Residency is a ready-to-move housing project by Trehan Group in Tapukara, Alwar Bypass Road, Bhiwadi. The community is planned for buyers seeking affordable 2 BHK apartments with convenient access to local healthcare, restaurants, schools, shopping, and industrial areas.',
      'The project offers 2 BHK apartments with sizes around 496 sq.ft. carpet area and resale options reported around 500 to 750 sq.ft. The project has an average price benchmark of approx. Rs 3.54 K per sq.ft. and a listed starting price of approx. Rs 17.58 Lac, making it a practical option for end-use and investment buyers in Tapukara.',
      'Trehan Delight Residency includes daily-life amenities such as swimming pool, solar lighting, fire safety, gymnasium, landscaped greens, water supply, car parking, school access, and gated community infrastructure. OMProperties can assist with site visit coordination, price clarity, legal documentation, and loan guidance.',
    ],
    amenities: [
      'Solar Lighting',
      'Garbage Disposal',
      'Swimming Pool',
      'Fire Sprinklers',
      'Vastu Compliant',
      'Landscaping & Tree Planting',
      'Gymnasium',
      'Fire Fighting System',
      '24X7 Water Supply',
      'Car Parking',
      'School',
      'Gated Community',
      'Security',
      'Lift',
      'Power Backup',
      'Video Door Security',
      'Parking Zone',
      'Maintained Staircases',
      'Green Surroundings',
      'Public Transport Access',
    ],
    nearbyPlaces: [
      'Tapukara Hospital - 1 min / approx. 0.6 km',
      'Shri Makhan Bhog nearby',
      'Tapukara locality',
      'Alwar Bypass Road connectivity',
      'DMart, shops, banks and ATMs nearby',
      'Schools and hospitals in the surrounding catchment',
      'Bhiwadi industrial and residential corridor',
    ],
    projectHighlights: [
      'Ready-to-move 2 BHK apartment project',
      'RERA registered: RAJ/P/2017/192',
      'Project area approx. 5 acres with 70% open area',
      '2 BHK configuration with 496 sq.ft. carpet area',
      'Average benchmark approx. Rs 3.54 K per sq.ft.',
      'EMI reference starts around Rs 9.31 K',
      'Resale options around 500-750 sq.ft.',
      'Reported project rating 4.8/5',
      'Home loan assistance available through reputed banks',
    ],
    unitTypes: [
      '2 BHK Apartment - 496 sq.ft. carpet area',
      '2 BHK resale options around 500 sq.ft.',
      '2 BHK resale options around 701 sq.ft.',
      '2 BHK resale options around 750 sq.ft.',
    ],
    socialHubAmenities: [
      'Swimming Pool',
      'Gymnasium',
      'Landscaping & Tree Planting',
      'Solar Lighting',
      'Car Parking',
      'School',
      '24X7 Water Supply',
      'Fire Fighting System',
      'Security',
      'Gated Community',
    ],
    locationAdvantages: [
      'Located in Tapukara on Alwar Bypass Road, Bhiwadi',
      'Tapukara Hospital within approx. 1 minute',
      'Restaurants, shops, banks and ATMs nearby',
      'Public transport availability around the project',
      'Good access to Bhiwadi residential and industrial zones',
    ],
    legalNote: 'RERA ID RAJ/P/2017/192. Verification and documentation assistance available.',
    map: 'https://maps.google.com/maps?q=Trehan%20Delight%20Residency%20Tapukara%20Bhiwadi&t=&z=14&ie=UTF8&iwloc=&output=embed',
  }
]

export const turnkeyServices = [
  {
    id: 1,
    slug: 'electrical',
    title: 'Electrical',
    summary: 'Safe, planned, and future-ready electrical execution for homes, offices, retail, and project sites.',
    hero: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=1200&q=80',
    features: ['Load planning', 'Concealed wiring', 'Panel installation', 'Lighting automation', 'Testing and handover'],
    gallery: [
      'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=900&q=80',
    ],
    description:
      'Our electrical team manages layout planning, wiring, panels, fixtures, inspections, and final handover with a focus on safety and easy maintenance.',
  },
  {
    id: 2,
    slug: 'interior',
    title: 'Interior',
    summary: 'Complete interior delivery from concept moodboards to modular execution and site finishing.',
    hero: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80',
    features: ['Space planning', 'False ceiling', 'Modular kitchen', 'Wardrobes', 'Material sourcing'],
    gallery: [
      'https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=900&q=80',
    ],
    description:
      'We deliver interiors with a practical eye for storage, lighting, finish quality, and daily usability while preserving a refined premium feel.',
  },
  {
    id: 3,
    slug: 'exterior',
    title: 'Exterior',
    summary: 'Facade, landscape, terrace, and outdoor finishing work for standout first impressions.',
    hero: 'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=80',
    features: ['Facade finishes', 'Outdoor lighting', 'Landscape work', 'Terrace design', 'Waterproofing coordination'],
    gallery: [
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1600607688066-890987f18a86?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1599427303058-f04cbcf4756f?auto=format&fit=crop&w=900&q=80',
    ],
    description:
      'Exterior work is handled through material selection, weather-aware detailing, vendor coordination, and disciplined site execution.',
  },
  {
    id: 4,
    slug: 'carpenter',
    title: 'Carpenter',
    summary: 'Custom carpentry, modular furniture, doors, partitions, and finish-grade woodwork.',
    hero: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=1200&q=80',
    features: ['Custom furniture', 'Door frames', 'Wall paneling', 'Storage units', 'Polishing and finishing'],
    gallery: [
      'https://images.unsplash.com/photo-1513467655676-561b7d489a88?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1530124566582-a618bc2615dc?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1581166397057-235af2b3c6dd?auto=format&fit=crop&w=900&q=80',
    ],
    description:
      'From wardrobes and kitchen shutters to feature walls and custom furniture, our carpentry work is measured, durable, and detail-led.',
  },
]

export const enquiries = [
  { id: 1, name: 'Rohit Mehra', subject: 'Golden Arc Residences', status: 'New', source: 'Property Enquiry' },
  { id: 2, name: 'Neha Kapoor', subject: 'Interior turnkey quote', status: 'Contacted', source: 'Turnkey Enquiry' },
  { id: 3, name: 'Amit Saini', subject: 'Commercial land options', status: 'New', source: 'Contact Form' },
]
