export const properties = [
  {
    id: 1,
    slug: 'golden-arc-residences',
    title: 'Golden Arc Residences',
    price: '₹1.45 Cr',
    location: 'Golf Course Extension Road, Gurugram',
    type: 'Flats',
    category: 'Residential',
    purpose: 'Buy',
    size: '1,850 sq.ft.',
    bedrooms: 3,
    bathrooms: 3,
    area: 1850,
    budget: 14500000,
    featured: true,
    amenities: ['Clubhouse', 'Covered Parking', 'Power Backup', 'Modular Kitchen', 'Security'],
    images: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?auto=format&fit=crop&w=1200&q=80',
    ],
    description:
      'A premium ready-to-move apartment with refined interiors, high-floor views, and excellent connectivity to business districts, schools, and retail destinations.',
    map: 'https://maps.google.com/maps?q=Golf%20Course%20Extension%20Road%20Gurugram&t=&z=13&ie=UTF8&iwloc=&output=embed',
  },
  {
    id: 2,
    slug: 'elysian-villa-estate',
    title: 'Elysian Villa Estate',
    price: '₹4.8 Cr',
    location: 'DLF Phase 2, Gurugram',
    type: 'Villas',
    category: 'Residential',
    purpose: 'Buy',
    size: '4,200 sq.ft.',
    bedrooms: 5,
    bathrooms: 5,
    area: 4200,
    budget: 48000000,
    featured: true,
    amenities: ['Private Lawn', 'Home Office', 'Servant Room', 'Terrace Deck', 'Gated Security'],
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?auto=format&fit=crop&w=1200&q=80',
    ],
    description:
      'A spacious independent villa designed for private family living, featuring generous bedrooms, lush outdoor space, and tasteful material finishes.',
    map: 'https://maps.google.com/maps?q=DLF%20Phase%202%20Gurugram&t=&z=13&ie=UTF8&iwloc=&output=embed',
  },
  {
    id: 3,
    slug: 'signature-retail-bay',
    title: 'Signature Retail Bay',
    price: '₹2.25 L / month',
    location: 'Sohna Road, Gurugram',
    type: 'Commercial Properties',
    category: 'Commercial',
    purpose: 'Lease',
    size: '2,600 sq.ft.',
    bedrooms: 0,
    bathrooms: 2,
    area: 2600,
    budget: 225000,
    featured: false,
    amenities: ['Main Road Frontage', 'Lift Access', 'Fire Safety', 'Dedicated Parking', 'High Footfall'],
    images: [
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80',
    ],
    description:
      'A highly visible commercial unit suitable for retail, showroom, or service-led businesses with robust infrastructure and signage exposure.',
    map: 'https://maps.google.com/maps?q=Sohna%20Road%20Gurugram&t=&z=13&ie=UTF8&iwloc=&output=embed',
  },
  {
    id: 4,
    slug: 'sector-83-investment-plot',
    title: 'Sector 83 Investment Plot',
    price: '₹1.1 Cr',
    location: 'Sector 83, Faridabad',
    type: 'Plots',
    category: 'Residential',
    purpose: 'Sell',
    size: '240 sq.yd.',
    bedrooms: 0,
    bathrooms: 0,
    area: 2160,
    budget: 11000000,
    featured: false,
    amenities: ['Clear Title', 'Wide Road', 'Park Facing', 'Registry Ready', 'Utilities Nearby'],
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1472224371017-08207f84aaae?auto=format&fit=crop&w=1200&q=80',
    ],
    description:
      'A well-positioned residential plot with clean documentation and practical dimensions for a custom family home or long-term investment.',
    map: 'https://maps.google.com/maps?q=Sector%2083%20Faridabad&t=&z=13&ie=UTF8&iwloc=&output=embed',
  },
  {
    id: 5,
    slug: 'oakline-family-house',
    title: 'Oakline Family House',
    price: '₹65,000 / month',
    location: 'Greater Kailash, New Delhi',
    type: 'Independent Houses',
    category: 'Residential',
    purpose: 'Rent',
    size: '2,300 sq.ft.',
    bedrooms: 4,
    bathrooms: 4,
    area: 2300,
    budget: 65000,
    featured: true,
    amenities: ['Independent Entry', 'Balcony', 'Water Storage', 'Pet Friendly', 'Two Car Parking'],
    images: [
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
    ],
    description:
      'A warm, functional family home in an established neighbourhood, close to markets, parks, metro access, and everyday conveniences.',
    map: 'https://maps.google.com/maps?q=Greater%20Kailash%20New%20Delhi&t=&z=13&ie=UTF8&iwloc=&output=embed',
  },
  {
    id: 6,
    slug: 'nh8-commercial-land',
    title: 'NH8 Commercial Land Parcel',
    price: '₹7.2 Cr',
    location: 'NH8 Corridor, Manesar',
    type: 'Commercial Lands',
    category: 'Commercial',
    purpose: 'Buy',
    size: '1.5 acres',
    bedrooms: 0,
    bathrooms: 0,
    area: 65340,
    budget: 72000000,
    featured: false,
    amenities: ['Highway Access', 'Industrial Belt', 'Boundary Wall', 'Approach Road', 'Investment Grade'],
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80',
    ],
    description:
      'A strategic commercial land parcel with strong frontage and logistics-friendly access for warehousing, institutional, or mixed-use planning.',
    map: 'https://maps.google.com/maps?q=Manesar%20NH8&t=&z=13&ie=UTF8&iwloc=&output=embed',
  },
  {
    id: 7,
    slug: 'rosewood-by-trimont',
    title: 'Rosewood by Trimont',
    price: 'Rs. 58.83 Lac - Rs. 77.66 Lac',
    location: 'Sector 16, Bhiwadi',
    type: 'Flats',
    category: 'Residential',
    purpose: 'Buy',
    size: '1,250 - 1,650 sq.ft.',
    bedrooms: 4,
    bedroomLabel: '2/3/4 Beds',
    bathrooms: 3,
    bathroomLabel: '2/3 Baths',
    area: 1650,
    budget: 7766000,
    featured: true,
    status: 'Available',
    verified: true,
    possessionStatus: 'Under Construction',
    projectArea: '17 Acres',
    towers: '18 Towers',
    totalUnits: '450 Units',
    completion: 'September 2027',
    furnishing: 'Unfurnished',
    parking: '1 Garage',
    floorNumber: 'Ground + 14',
    totalFloors: '14',
    reraNumber: 'Verification assistance available',
    nearbyPlaces: [
      '5 min from NH 48, Delhi-Jaipur Highway',
      '5 min from proposed Alwar-Delhi RRTS Metro, Dharuhera',
      '35-40 min from Rajiv Chowk, Gurgaon',
      '60 min from Indira Gandhi International Airport',
      'Schools, hospitals, malls, and industrial hubs within 5-25 min',
    ],
    amenities: [
      'Grand Clubhouse',
      'Half Olympic-size Swimming Pool',
      'Pickleball Court',
      'Badminton Court',
      'Basketball Court',
      'Kids Play Area',
      'Open Gym',
      'Yoga Zone',
      'Jogging Track',
      'Landscaped Greens',
      'Reserved Parking',
      'Power Backup',
      'Security',
      'Visitor Parking',
      'Waste Disposal',
    ],
    images: [
      '/properties/rosewood/project-view.webp',
      '/properties/rosewood/pool-deck.webp',
      '/properties/rosewood/masterplan.webp',
      '/properties/rosewood/landscape-sports.webp',
      '/properties/rosewood/balcony-view.webp',
      '/properties/rosewood/basketball-court.webp',
      '/properties/rosewood/tennis-court.webp',
      '/properties/rosewood/location-map.webp',
    ],
    description:
      'Rosewood by Trimont is a thoughtfully planned under-construction residential apartment project in Sector 16, Bhiwadi, offering 2 BHK, 3 BHK and 4 BHK homes. Designed around open greens, large balconies, landscaped gardens, sports courts and a modern clubhouse, the project blends luxury, comfort and practical connectivity near Alwar Bypass Road and NH 48.',
    longDescription: [
      'Rosewood by Trimont is a seamless amalgamation of luxury, comfort and style, planned to provide a truly sophisticated lifestyle in Bhiwadi. These residential apartments are designed to create a calm, well-ventilated and uncluttered living environment, with open green spaces that make everyday life feel more relaxed and refined.',
      'Developed by Trimont Group on Alwar Bypass Road, Bhiwadi, the project focuses on customer satisfaction, quality standards, innovation and timely delivery. Trimont Rosewood offers 2 BHK, 3 BHK and 4 BHK apartments with large balconies, practical layouts, modern amenities and excellent public transport connectivity.',
      'Spread across a large residential campus with multiple towers, landscaped greens, a grand entrance, sports courts and a modern social hub, Trimont Rosewood is positioned as a strong residential and investment opportunity for buyers looking at Bhiwadi and the Alwar Bypass Road corridor.',
    ],
    projectHighlights: [
      '2/3/4 BHK apartments',
      'Project area of approx. 17 acres',
      '18 towers',
      'Ground + 14 storey towers',
      'More than 80% open area',
      'Located on 4 lane mega highway, 200 ft Alwar Bypass Road',
      'Beautifully landscaped gardens',
      'Grand entrance with water bodies',
      'Ultra modern club and swimming pool',
      'Large balconies',
      'Spacious lift lobby',
      '4 apartments on one floor with 2 lifts in 2 BHK apartments',
      '3 apartments on one floor with 2 lifts in 3 BHK apartments',
      'All tower structures ready',
      'Project completion expected in September 2027',
    ],
    socialHubAmenities: [
      'Approx. 150,000 sq.ft. social hub',
      'Grand clubhouse',
      'Half Olympic-size swimming pool',
      'Pickleball court',
      'Landscaped greens',
      'Kids play area',
      'Box cricket area',
      'Badminton court',
      'Basketball court',
      'Splash pool for kids',
      'Open gym',
      'Yoga zone',
      'Gazebo for senior citizens',
      'Sitting area',
      'Lawn',
      'Jogging/walking path',
      'Rose garden',
      'Golf cart',
    ],
    unitTypes: [
      '2 BHK - 1,250 sq.ft.',
      '3 BHK - 1,650 sq.ft.',
      '4 BHK - 2,750 sq.ft.',
    ],
    locationAdvantages: [
      'Bang on Alwar-Bhiwadi Road',
      '5 min drive from NH 48, Delhi-Jaipur Highway',
      '5 min from proposed Alwar-Delhi RRTS Metro, Dharuhera',
      '60 min from Indira Gandhi International Airport',
      '35-40 min from Rajiv Chowk, Gurgaon',
      'Proposed RRTS Metro Station at Dharuhera within 5 min',
      'Panchgaon proposed RRTS within 15 min',
      'IMT Manesar via proposed RRTS within 20 min',
      'GD Goenka Public School within 10 min',
      'Delhi Public School International within 15 min',
      'St. Xavier\'s School within 5 min',
      'Sri Krishna Hospital within 5 min',
      'Hari Ram Hospital within 5 min',
      'Genesis Mall within 3 min',
      'Legend Centra Mall within 2 min',
      'Reliance Smart Superstore within 2 min',
      'D Mart within 10 min',
      'Industrial hubs including KEI, Jaquar, Lenskart, Honda and Saint Gobain within 20-25 min',
    ],
    map: 'https://maps.google.com/maps?q=Sector%2016%20Bhiwadi%20Rajasthan&t=&z=14&ie=UTF8&iwloc=&output=embed',
  },
  {
    id: 8,
    slug: 'greenwood-city-bhiwadi-tijara-highway',
    title: 'Green Wood City Plotted Development',
    price: 'Rs. 12,900 per sq. yd.',
    location: 'Bhiwadi-Tijara Highway, SH-25, Bhiwadi',
    type: 'Plots',
    category: 'Residential',
    purpose: 'Buy',
    size: '105 - 200 sq. yd.',
    bedrooms: 0,
    bathrooms: 0,
    area: 1800,
    budget: 1354500,
    featured: true,
    status: 'Available',
    verified: true,
    possessionStatus: 'Launch Offer',
    projectArea: '9 Bigha plotted development',
    reraNumber: 'Verification assistance available',
    brochureUrl: '/properties/greenwood-city/brochure.pdf',
    videoUrl: '/properties/greenwood-city/site-video.mp4',
    amenities: [
      'Gated Community',
      'Wide Roads',
      'Park & Green Area',
      '24x7 Security',
      'Priority Allotment',
      'Limited Inventory',
      'Highway Location',
      'Investment Potential',
    ],
    images: [
      '/properties/greenwood-city/launch-offer.jpeg',
      '/properties/greenwood-city/site-plan.png',
    ],
    description:
      'Green Wood City is a premium plotted development launch on Bhiwadi-Tijara Highway, SH-25, offering limited plots with exclusive launch pricing and strong investment potential.',
    longDescription: [
      'Green Wood City is a premium plotted development launch located bang on SH-25, Bhiwadi-Tijara Highway. The project offers buyers an opportunity to own residential plots in a growing Bhiwadi corridor with highway visibility and strong future potential.',
      'The launch offer includes tentative plot sizes from approx. 105 to 200 sq. yds. at Rs. 12,900 per sq. yd., with an exclusive inaugural saving of Rs. 900 per sq. yd. for limited inventory. The offer is valid for the next 15 days only.',
      'This launch is positioned for buyers looking for priority allotment, lowest pricing in Bhiwadi, excellent investment potential and early access to the best plots in the township.',
    ],
    projectHighlights: [
      'Premium plotted development on Bhiwadi-Tijara Highway',
      'Bang on SH-25 Bhiwadi',
      'Tentative plot sizes approx. 105-200 sq. yds.',
      'Launch price Rs. 12,900 per sq. yd.',
      'Exclusive offer saves Rs. 900 per sq. yd.',
      'Offer valid for the next 15 days only',
      'Limited inventory available',
      'Priority allotment of best plots',
      'Lowest pricing in Bhiwadi',
      'Excellent investment potential',
    ],
    socialHubAmenities: [
      'Gated community',
      'Wide roads',
      'Park and green area',
      '24x7 security',
      'Plotted township planning',
      'Highway frontage advantage',
    ],
    unitTypes: [
      'Approx. 105 sq. yd. plots',
      'Approx. 150 sq. yd. plots',
      'Approx. 200 sq. yd. plots',
    ],
    locationAdvantages: [
      'Located on Bhiwadi-Tijara Highway',
      'Bang on SH-25 Bhiwadi',
      'Good visibility and access from highway corridor',
      'Suitable for residential investment and future appreciation',
      'Connected to Bhiwadi growth corridor',
    ],
    nearbyPlaces: [
      'Bhiwadi-Tijara Highway',
      'SH-25 Bhiwadi',
      'Bhiwadi growth corridor',
    ],
    legalNote: 'Registry charges, government charges and documentation charges payable extra as applicable.',
    map: 'https://www.google.com/maps/embed?pb=!1m17!1m12!1m3!1d1099.9102587864916!2d76.84115002508645!3d27.999277541820728!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m2!1m1!2zMjfCsDU5JzU1LjgiTiA3NsKwNTAnMjguMyJF!5e0!3m2!1sen!2sin!4v1783861768086!5m2!1sen!2sin',
  },
]

export const turnkeyServices = [
  {
    id: 1,
    slug: 'electrical',
    title: 'Electrical',
    summary: 'Safe, planned, and future-ready electrical execution for homes, offices, retail, and project sites.',
    hero: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=1200&q=80',
    features: ['Load planning', 'Concealed wiring', 'Panel installation', 'Lighting automation', 'Testing and handover'],
    gallery: [
      'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=900&q=80',
    ],
    description:
      'Our electrical team manages layout planning, wiring, panels, fixtures, inspections, and final handover with a focus on safety and easy maintenance.',
  },
  {
    id: 2,
    slug: 'interior',
    title: 'Interior',
    summary: 'Complete interior delivery from concept moodboards to modular execution and site finishing.',
    hero: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80',
    features: ['Space planning', 'False ceiling', 'Modular kitchen', 'Wardrobes', 'Material sourcing'],
    gallery: [
      'https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=900&q=80',
    ],
    description:
      'We deliver interiors with a practical eye for storage, lighting, finish quality, and daily usability while preserving a refined premium feel.',
  },
  {
    id: 3,
    slug: 'exterior',
    title: 'Exterior',
    summary: 'Facade, landscape, terrace, and outdoor finishing work for standout first impressions.',
    hero: 'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=80',
    features: ['Facade finishes', 'Outdoor lighting', 'Landscape work', 'Terrace design', 'Waterproofing coordination'],
    gallery: [
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1600607688066-890987f18a86?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1599427303058-f04cbcf4756f?auto=format&fit=crop&w=900&q=80',
    ],
    description:
      'Exterior work is handled through material selection, weather-aware detailing, vendor coordination, and disciplined site execution.',
  },
  {
    id: 4,
    slug: 'carpenter',
    title: 'Carpenter',
    summary: 'Custom carpentry, modular furniture, doors, partitions, and finish-grade woodwork.',
    hero: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=1200&q=80',
    features: ['Custom furniture', 'Door frames', 'Wall paneling', 'Storage units', 'Polishing and finishing'],
    gallery: [
      'https://images.unsplash.com/photo-1513467655676-561b7d489a88?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1530124566582-a618bc2615dc?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1581166397057-235af2b3c6dd?auto=format&fit=crop&w=900&q=80',
    ],
    description:
      'From wardrobes and kitchen shutters to feature walls and custom furniture, our carpentry work is measured, durable, and detail-led.',
  },
]

export const enquiries = [
  { id: 1, name: 'Rohit Mehra', subject: 'Golden Arc Residences', status: 'New', source: 'Property Enquiry' },
  { id: 2, name: 'Neha Kapoor', subject: 'Interior turnkey quote', status: 'Contacted', source: 'Turnkey Enquiry' },
  { id: 3, name: 'Amit Saini', subject: 'Commercial land options', status: 'New', source: 'Contact Form' },
]
